import { Inter } from 'next/font/google'
import './globals.css'
import 'animate.css'
import { Toaster } from '@/components/ui/sonner'
import NextThemeProvider from '@/provider/themeProvider'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <NextThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    enableSystem={false}
                    disableTransitionOnChange
                >
                    {children}
                    <Toaster />
                </NextThemeProvider>
            </body>
        </html>
    )
}
